# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6de4aa99793eef3395011a8bf20e31f40f17f1814c3624f5119555863ae9c91ceaffaec7b296f682af12d2e2a8f7b75d816d890e1b7ef5b310d1634b45116ad9

test:
  secret_key_base: eaa9d38c44883c4275c7b0257f1f0f2b2f6e6414901b5bbc5738f32b73cfbcc11864e794c31e87b739d7ffa18f2f1c49becbfdb0f7d252fc352883d1d6d87d5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
